package it.webscience.kpeople.dal.exception;

/**
 * Classe relativa ad un'eccezione generica del livello DAL.
 */
public class KPeopleSesameException extends Exception {

    /**
     * Costruttore che definisce il messaggio dell'eccezione.
     * @param message messaggio dell'eccezione
     */
    public KPeopleSesameException(final String message) {
        super(message);
    }

    /**
     * Autogenerated serialVersionUID.
     */
    private static final long serialVersionUID = 3397774427977323925L;

}
