package it.webscience.kpeople.dal.exception;

import org.openrdf.repository.RepositoryException;

/**
 * Classe relativa ad un'eccezione generica del livello DAL.
 */
public class KPeopleDAOException extends Exception {

    /**
     * Costruttore di default.
     */
    public KPeopleDAOException() {
        super();
    }

    /**
     * Costruttore che definisce il messaggio dell'eccezione.
     * @param message messaggio dell'eccezione
     */
    public KPeopleDAOException(final String message) {
        super(message);
    }

    /**
     * Costruttore che accetta un oggetto throwable per preservare
     * lo stack trace.
     * @param e eccezione
     */
    public KPeopleDAOException(final Throwable e) {
        super(e);
    }

    /**
     * Costruttore che definisce il messaggio dell'eccezione.
     * @param message messaggio dell'eccezione
     * @param e eccezione
     */
    public KPeopleDAOException(final String message, final Throwable e) {
        super(message, e);
    }

    /**
     * Autogenerated serialVersionUID.
     */
    private static final long serialVersionUID = 3397774427977323925L;

}
