//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.1
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPOutlookAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KPLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KPLanguage() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPOutlookAddIn.Resources.KPLanguage", typeof(KPLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Closed.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kpeople Plug-In ERROR.
        /// </summary>
        internal static string errorCaption {
            get {
                return ResourceManager.GetString("errorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert.
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The service Kpeople is unreachable, verify network connectivity..
        /// </summary>
        internal static string networkError {
            get {
                return ResourceManager.GetString("networkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opened.
        /// </summary>
        internal static string opened {
            get {
                return ResourceManager.GetString("opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Associated processes.
        /// </summary>
        internal static string ribbonGroup0 {
            get {
                return ResourceManager.GetString("ribbonGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonGroup0Label0 {
            get {
                return ResourceManager.GetString("ribbonGroup0Label0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonGroup0Label1 {
            get {
                return ResourceManager.GetString("ribbonGroup0Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Associated processes.
        /// </summary>
        internal static string ribbonGroup1 {
            get {
                return ResourceManager.GetString("ribbonGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonGroup1Label0 {
            get {
                return ResourceManager.GetString("ribbonGroup1Label0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonGroup1Label1 {
            get {
                return ResourceManager.GetString("ribbonGroup1Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonGroup1Label2 {
            get {
                return ResourceManager.GetString("ribbonGroup1Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kpeople.
        /// </summary>
        internal static string ribbonKpeopleGroup {
            get {
                return ResourceManager.GetString("ribbonKpeopleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string ribbonKpeopleGroupButton {
            get {
                return ResourceManager.GetString("ribbonKpeopleGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kpeople.
        /// </summary>
        internal static string ribbonLabel {
            get {
                return ResourceManager.GetString("ribbonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search....
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search a process.
        /// </summary>
        internal static string searchProcess {
            get {
                return ResourceManager.GetString("searchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KPeople tag.
        /// </summary>
        internal static string tagSelector {
            get {
                return ResourceManager.GetString("tagSelector", resourceCulture);
            }
        }
    }
}
